/** Edge-safe key projection of the checked Constitute topic taxonomy. */
const TOPIC_KEYS = new Set(
  "abide access acfree achighed adage adres adsel adterm adtermn amend amparo anthem appeal arms artists assem assets assoc asylum atgen attend auth balbudgt bank binding budget busines cabdiss cabinet cabpow cabrest cabsel camppubf capital cappun cc census childpro childwrk citdep citizen citren citrev civil civilmil civmar colony comchief commit compvote conage concop conlim conpow conrem conres conright consel conterm corppun couns cruelty cultrght custlaw debtors depexec devlpers dignity district divhouse doubjep dueproc ecage ecom econplan ecpow ecrdet ecres ecsel ecterm ecterml edcomp edfree electsch em env equal equalgr1 equalgr10 equalgr11 equalgr12 equalgr13 equalgr14 equalgr15 equalgr16 equalgr2 equalgr3 equalgr4 equalgr5 equalgr6 equalgr7 equalgr8 equalgr9 ethincl evidence examwit excrim execindp execnum expost express exprop exsess fairtri falseimp fedrev fedsep figures finance finsup1 finsup2 finsup3 finsup4 flag fndfam freecomp freeelec freemove freerel god govmed habcorp headforn health hocage hocop hocres hocsel hocsize hocterm hocterml hogage hogdec hogdiss hogdlim hogelect hogimm hoglegr hogpow hogrest hogsucc hogterm hogterml hosage hosdec hosdiss hoselect hosimm hospow hosrest hosstaff hossucc hosterm hosterml housenum hr illadmin illsub immunity inalrght income indcit indpolgr1 indpolgr2 indpolgr3 indpolgr4 indpolgr5 indpolgr6 infoacc initiat interp intlaw intorgs intprop intrght invexe jc jointrde jrem judcrts1 judcrts2 judcrts3 judcrts4 judcrts5 judcrts6 judcrts7 judcrts8 judind judprec judretir judsal jury juvenile lang langprot legapp legdiss legini legjoint legrep legsupr leisure levjud lhage lhlead lhquota lhrest lhseats lhselect lhspleg lhterm lhtrmlim libel life marriage matequal medcom milcom milrest milserv miranda motive motto mun natcit nomil oath occupate offrel ombuds opgroup opinion ordage ordres ordsel ordterm ordterml orglaw override overthrw pardon parents partprf partprh partreg partrght partunco petition preamble prerel presinoc press prevcond prevlead prisonrg privacy profleg proprght provwork prtyduty pubmeet pubmin pubtri quorum radio recvote referen region rellaw reltax remleg remuner resenex resrce rightres safework science scifree seccess selfdet seprel session shelter slave socclas solid speedtri spend standliv stdcom strike sub suppow system tax taxes telecom terror torture tranprov transfer treat treatcon trilang truthcom tv uhage uhlead uhquota uhrest uhseats uhselect uhspleg uhterm uhtrmlim unamend uncon vicright voteres voteun war water wolaw work amendment culture_and_identity elections executive federalism international_law judiciary legislature principles_and_symbols regulation_and_oversight rights_and_duties special_sections".split(
    " ",
  ),
);

export function isKnownConstitutionTopic(key: string): boolean {
  return TOPIC_KEYS.has(key);
}

export function knownConstitutionTopicKeys(): string[] {
  return [...TOPIC_KEYS].sort();
}
