/**
 * PLT-008 — canonical security/exposure inventory of every route.ts
 * handler under src/app (100 files: public API, admin, cron, chat,
 * pulse-coding, embed, export/downloads).
 *
 * This registry is the SOLE source of truth for route exposure
 * classification, mutation/sensitivity flags, and declared controls.
 * `scripts/validate-route-inventory.ts` walks the filesystem for the
 * real `route.ts` list and the real exported HTTP methods, then runs
 * the pure comparison functions in `./checks.ts` against this array —
 * failing the build on a phantom route (on disk, not registered), a
 * stale entry (registered, not on disk), or a methods drift (registry
 * says X, source exports Y).
 *
 * `controls` is a closed set of declared protection mechanisms:
 *   - "admin-session"         gated on getAdminSession() (owner cookie)
 *   - "pulse-coding-session"  gated on getPulseCodingSession() (coder/adjudicator cookie)
 *   - "oauth-bootstrap"       pre-session OAuth step (CSRF state cookie + account allowlist)
 *   - "credential-check"      the login route itself: username/password or access-code verification
 *   - "cron-secret"           gated on requireCronAuth() / CRON_SECRET bearer token
 *   - "rate-limit"            shared HMAC-subject/Neon rate limiting
 *   - "platform-rate-limit"   externally verified Vercel WAF rate limiting
 *   - "same-origin-mutation"  exact-origin/Fetch-Metadata CSRF guard
 *   - "admin-audit"           common actor/action/target/result audit ledger
 *   - "input-validation"      schema/hand-rolled field validation before use
 *   - "public"                intentionally open; no auth (read-only or static)
 *
 * `findUncontrolledMutations` in ./checks.ts flags any mutation or
 * sensitive entry whose controls don't match its exposure class's
 * minimum bar (cron -> cron-secret; admin/pulse-coding -> a session
 * control or documented oauth-bootstrap; public-mutation ->
 * input-validation or rate-limit). `scripts/validate-route-inventory.ts`
 * only fails the build on an UNDOCUMENTED uncontrolled finding (empty
 * `note`); a documented one is printed prominently but does not fail,
 * per PLT-008's "flag, don't hide" mandate.
 */

export type RouteExposure =
  | "public-read"
  | "public-mutation"
  | "admin"
  | "cron"
  | "chat"
  | "embed"
  | "export"
  | "pulse-coding"
  | "internal";

export type HttpMethod =
  "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS";

export type RouteControl =
  | "admin-session"
  | "pulse-coding-session"
  | "oauth-bootstrap"
  | "credential-check"
  | "cron-secret"
  | "rate-limit"
  | "platform-rate-limit"
  | "same-origin-mutation"
  | "admin-audit"
  | "input-validation"
  | "public";

export interface RouteInventoryEntry {
  /** Repo path relative to src/app, e.g. "api/v1/countries/route.ts" —
   *  matches `find src/app -name route.ts | sed 's|src/app/||'`. */
  filePath: string;
  exposure: RouteExposure;
  /** HTTP methods this route.ts exports a handler for. */
  methods: HttpMethod[];
  /** True if methods includes POST, PUT, PATCH, or DELETE. */
  mutation: boolean;
  /** True for admin/cron/chat/pulse-coding exposure, or any route that
   *  collects/returns PII. */
  sensitive: boolean;
  controls: RouteControl[];
  note: string;
}

export const ROUTE_INVENTORY: RouteInventoryEntry[] = [
  {
    filePath: "api/admin/advisory-applications/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Updates or deletes an advisory application through the shared active-session, exact-origin, and common audit boundary.",
  },
  {
    filePath: "api/admin/advisory-applications/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["admin-session"],
    note: "Lists advisory applicant PII (name/email/affiliation); gated on getAdminSession().",
  },
  {
    filePath: "api/admin/contact/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["admin-session"],
    note: "Lists contact-form submitter PII; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/data-disputes/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Resolves/reopens data disputes through the shared active-session, exact-origin, and common audit boundary plus the domain audit log.",
  },
  {
    filePath: "api/admin/google/callback/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["oauth-bootstrap", "rate-limit"],
    note: "Pre-session OAuth code exchange: a shared 10/15min bootstrap budget runs before upstream work, then the short-lived CSRF state cookie and exact ADMIN_GOOGLE_EMAIL allowlist gate session issuance.",
  },
  {
    filePath: "api/admin/google/start/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["oauth-bootstrap", "rate-limit"],
    note: "Mints a short-lived HttpOnly CSRF state cookie and redirects to Google only after the shared 10/15min OAuth-bootstrap budget allows the request.",
  },
  {
    filePath: "api/admin/messages/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Updates a contact submission through the shared active-session, exact-origin, and common audit boundary.",
  },
  {
    filePath: "api/admin/pulse-review/[id]/exception/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Grants a review-SLA exception through the shared active-session, exact-origin, and common audit boundary.",
  },
  {
    filePath: "api/admin/pulse-review/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Reviews a Pulse event through the shared active-session, exact-origin, and common audit boundary plus the domain audit log.",
  },
  {
    filePath: "api/admin/session/route.ts",
    exposure: "admin",
    methods: ["DELETE", "POST"],
    mutation: true,
    sensitive: true,
    controls: [
      "credential-check",
      "rate-limit",
      "same-origin-mutation",
      "admin-session",
      "admin-audit",
    ],
    note: "POST is the exact-origin, durably throttled constant-time credential bootstrap and records successful issuance; DELETE uses the shared signed-session revocation and audit boundary.",
  },
  {
    filePath: "api/admin/sign-out/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Idempotent logout verifies any signed envelope, persists a hashed revocation tombstone, records the outcome, then clears cookies; missing/expired cookies only clear after exact-origin validation.",
  },
  {
    filePath: "api/advisory-applications/route.ts",
    exposure: "public-mutation",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public advisory-board application intake; shared HMAC/Neon limit (5/30min) plus validateAdvisoryApplication() field/length checks. Collects applicant PII.",
  },
  {
    filePath: "api/chat/route.ts",
    exposure: "chat",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public Ask Civica proxy to a paid Anthropic model; shared burst (15/min) and sustained (100/hour) HMAC/Neon budgets plus hard input-size/shape caps run before any model call.",
  },
  {
    filePath: "api/citations/[entityType]/[id]/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "ATL-019 stable-entity citation resolver; shared public-dynamic-read budget, no PII, and no authentication required by design.",
  },
  {
    filePath: "api/citations/[entityType]/[id]/history/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "ATL-020 public, field-safe release-history projection keyed by ATL-019 stable entity identity; never returns raw retained snapshots.",
  },
  {
    filePath: "api/civica-index/corrections/route.ts",
    exposure: "public-mutation",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public correction intake; shared HMAC/Neon limit (5/10min) plus category/dimension/email/length checks. Collects optional submitter PII.",
  },
  {
    filePath: "api/constitution/excerpts/notable/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public constitution read using the shared public-dynamic-read budget; no PII or authentication.",
  },
  {
    filePath: "api/constitution/excerpts/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public constitution read using the shared public-dynamic-read budget; no PII or authentication.",
  },
  {
    filePath: "api/constitution/passages/[digest]/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public stable-passage read using the shared public-dynamic-read budget; no PII or authentication.",
  },
  {
    filePath: "api/constitution/search/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Indexed constitution search uses a shared 30/min HMAC/Neon budget before its bounded query transaction.",
  },
  {
    filePath: "api/contact/route.ts",
    exposure: "public-mutation",
    methods: ["OPTIONS", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public contact-form intake; shared HMAC/Neon limit (5/10min) plus email/length validation. Collects submitter PII.",
  },
  {
    filePath: "api/observability/client-error/route.ts",
    exposure: "public-mutation",
    methods: ["POST"],
    mutation: true,
    sensitive: false,
    controls: ["rate-limit", "input-validation"],
    note: "Content-free client-boundary signal; a shared HMAC/Neon limit and a strict two-field schema run before the server reduces the pathname to a route template.",
  },
  {
    filePath: "api/countries/[slug]/bills/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/constitution/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/democracy/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/export/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "DAT-027 rights-filtered country export; shared 30/min dynamic-export budget runs before data assembly. Read-only and no PII.",
  },
  {
    filePath: "api/countries/[slug]/indicator-history/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Rights-filtered indicator-history export using the shared 30/min dynamic-export budget; no PII or authentication.",
  },
  {
    filePath: "api/countries/[slug]/international/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/leaders/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/scores/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/structure/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/cron/bills/br/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/ca/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/de/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/fr/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/uk/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/us/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/auto-resolve-disputes/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/refresh-cache/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/snapshot-vintage/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-cia-cabinets/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-classifications/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-eurostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-fao-faostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ibge-br/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ilo-ilostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-imf-weo/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-insee-fr/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-oecd-stat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-officeholders/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ons-uk/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-statcan-ca/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-stats-sa/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-un-data/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-undp-hdi/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-unesco-uis/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-us-census/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wdi/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-who-gho/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wikidata/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wto-stats/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/verify-reconciliation/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/calculate/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/classify/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/ingest/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/classify/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/cluster/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/ingest/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/review-sla/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/score/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/operations/error-alerts/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() protects the content-free error-alert check before any retained monitoring event is read.",
  },
  {
    filePath: "api/cron/operations/pipeline-alerts/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() protects the retained production-pipeline alert check before any run detail is read.",
  },
  {
    filePath: "api/cron/operations/health-alerts/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() protects the content-free health report and owner alert check before any component state is read.",
  },
  {
    filePath: "api/governance-evidence/[slug]/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public Governance Evidence export using the shared 30/min dynamic-export budget; no PII or authentication.",
  },
  {
    filePath: "api/health/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["platform-rate-limit", "public"],
    note: "Public, content-free availability contract for the independent monitor and status page; the verified all-path platform WAF supplies flood protection without making a database-backed limiter part of the database probe.",
  },
  {
    filePath: "api/metrics/[metricId]/strip-data/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public metric-strip read using the shared public-dynamic-read budget; no PII or authentication.",
  },
  {
    filePath: "api/provenance-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/pulse-coding/adjudications/[assignmentId]/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Records a blinded adjudication decision; gated on getPulseCodingSession() with an explicit adjudicator-role check.",
  },
  {
    filePath: "api/pulse-coding/admin/participants/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session", "same-origin-mutation", "admin-audit"],
    note: "Issues a participant through the owner-admin shared active-session, exact-origin, and common audit boundary; the coding domain also writes participant/assignment audit rows.",
  },
  {
    filePath: "api/pulse-coding/assignments/[id]/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Saves/locks a blinded coding submission; gated on getPulseCodingSession().",
  },
  {
    filePath: "api/pulse-coding/exports/[studyId]/route.ts",
    exposure: "pulse-coding",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Exports a coding study artifact; gated on getPulseCodingSession() (any participant), with a further per-study authorization check inside exportPulseCodingStudy() (403 on mismatch).",
  },
  {
    filePath: "api/pulse-coding/session/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["credential-check", "rate-limit", "same-origin-mutation"],
    note: "Exact-origin pulse-coding sign-in authenticates an issued access code after the shared 5/15min credential-bootstrap budget allows the request.",
  },
  {
    filePath: "api/pulse-coding/sign-out/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["platform-rate-limit", "same-origin-mutation"],
    note: "Exact-origin logout performs only a browser-cookie clear and remains under the verified all-path WAF ceiling. OPEN FINDING (bounded): participant credential revocation remains the server-side invalidation path.",
  },
  {
    filePath: "api/reconciliation-audit/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/rights-manifest/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/source-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/v1/conditions/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned Conditions release API; CORS-open, per-IP rate limited, and returns only one immutable release selected by its optional release id.",
  },
  {
    filePath: "api/v1/countries/[code]/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/countries/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/elections/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/government-types/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/[country_slug]/history/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/[country_slug]/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/by-government-type/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/compare/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/methodology/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/rankings/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/peer-groupings/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/[country_slug]/dimensions/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/[country_slug]/events/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/changelog/v2/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/cluster-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/methodology/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/source-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "downloads/civica-atlas-2026-07-11.json.gz/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["platform-rate-limit", "public"],
    note: "Serves the checked frozen release from disk; the verified all-path Vercel WAF supplies 600/60s/IP challenge protection without request-time DB access.",
  },
  {
    filePath: "downloads/civica-atlas-2026-07-11.manifest.json/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["platform-rate-limit", "public"],
    note: "Serves the checked frozen manifest from disk; the verified all-path Vercel WAF supplies 600/60s/IP challenge protection without request-time DB access.",
  },
  {
    filePath: "embed/[slug]/route.ts",
    exposure: "embed",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["platform-rate-limit", "public"],
    note: "Retired static replacement-link embed with no data access; the verified all-path Vercel WAF supplies 600/60s/IP challenge protection.",
  },
];

export function getRouteInventoryEntry(filePath: string): RouteInventoryEntry {
  const entry = ROUTE_INVENTORY.find((r) => r.filePath === filePath);
  if (!entry) throw new Error(`Unknown route inventory entry: ${filePath}`);
  return entry;
}
