/**
 * PLT-008 — canonical security/exposure inventory of every route.ts
 * handler under src/app (99 files: public API, admin, cron, chat,
 * pulse-coding, embed, export/downloads).
 *
 * This registry is the SOLE source of truth for route exposure
 * classification, mutation/sensitivity flags, and declared controls.
 * `scripts/validate-route-inventory.ts` walks the filesystem for the
 * real `route.ts` list and the real exported HTTP methods, then runs
 * the pure comparison functions in `./checks.ts` against this array —
 * failing the build on a phantom route (on disk, not registered), a
 * stale entry (registered, not on disk), or a methods drift (registry
 * says X, source exports Y).
 *
 * `controls` is a closed set of declared protection mechanisms:
 *   - "admin-session"         gated on getAdminSession() (owner cookie)
 *   - "pulse-coding-session"  gated on getPulseCodingSession() (coder/adjudicator cookie)
 *   - "oauth-bootstrap"       pre-session OAuth step (CSRF state cookie + account allowlist)
 *   - "credential-check"      the login route itself: username/password or access-code verification
 *   - "cron-secret"           gated on requireCronAuth() / CRON_SECRET bearer token
 *   - "rate-limit"            per-IP in-memory and/or durable rate limiting
 *   - "input-validation"      schema/hand-rolled field validation before use
 *   - "public"                intentionally open; no auth (read-only or static)
 *
 * `findUncontrolledMutations` in ./checks.ts flags any mutation or
 * sensitive entry whose controls don't match its exposure class's
 * minimum bar (cron -> cron-secret; admin/pulse-coding -> a session
 * control or documented oauth-bootstrap; public-mutation ->
 * input-validation or rate-limit). Two real, intentionally-uncontrolled
 * findings are recorded here rather than hidden: the admin and
 * pulse-coding sign-out routes clear cookies with no session check
 * (benign — see their notes). `scripts/validate-route-inventory.ts`
 * only fails the build on an UNDOCUMENTED uncontrolled finding (empty
 * `note`); a documented one is printed prominently but does not fail,
 * per PLT-008's "flag, don't hide" mandate.
 */

export type RouteExposure =
  | "public-read"
  | "public-mutation"
  | "admin"
  | "cron"
  | "chat"
  | "embed"
  | "export"
  | "pulse-coding"
  | "internal";

export type HttpMethod =
  | "GET"
  | "POST"
  | "PUT"
  | "PATCH"
  | "DELETE"
  | "HEAD"
  | "OPTIONS";

export type RouteControl =
  | "admin-session"
  | "pulse-coding-session"
  | "oauth-bootstrap"
  | "credential-check"
  | "cron-secret"
  | "rate-limit"
  | "input-validation"
  | "public";

export interface RouteInventoryEntry {
  /** Repo path relative to src/app, e.g. "api/v1/countries/route.ts" —
   *  matches `find src/app -name route.ts | sed 's|src/app/||'`. */
  filePath: string;
  exposure: RouteExposure;
  /** HTTP methods this route.ts exports a handler for. */
  methods: HttpMethod[];
  /** True if methods includes POST, PUT, PATCH, or DELETE. */
  mutation: boolean;
  /** True for admin/cron/chat/pulse-coding exposure, or any route that
   *  collects/returns PII. */
  sensitive: boolean;
  controls: RouteControl[];
  note: string;
}

export const ROUTE_INVENTORY: RouteInventoryEntry[] = [
  {
    filePath: "api/admin/advisory-applications/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Flips advisory-application triage status; gated on the admin session cookie via getAdminSession().",
  },
  {
    filePath: "api/admin/advisory-applications/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["admin-session"],
    note: "Lists advisory applicant PII (name/email/affiliation); gated on getAdminSession().",
  },
  {
    filePath: "api/admin/contact/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["admin-session"],
    note: "Lists contact-form submitter PII; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/data-disputes/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Resolves/reopens data disputes with audit-log write; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/google/callback/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["oauth-bootstrap"],
    note: "Pre-session OAuth code exchange: verifies the short-lived CSRF state cookie AND an exact ADMIN_GOOGLE_EMAIL allowlist match before ever issuing an admin session cookie. Cannot itself require admin-session (it is what establishes one) — the state cookie + allowlist match is the control.",
  },
  {
    filePath: "api/admin/google/start/route.ts",
    exposure: "admin",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["oauth-bootstrap"],
    note: "Mints a short-lived HttpOnly CSRF state cookie and 303s to Google; no data access. Pre-session by design (kicks off the login flow the callback route verifies).",
  },
  {
    filePath: "api/admin/messages/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Flips a contact submission's triage status; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/pulse-review/[id]/exception/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Grants a review-SLA exception; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/pulse-review/[id]/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Approves/edits/rejects a Pulse event with audit-log write; gated on getAdminSession().",
  },
  {
    filePath: "api/admin/session/route.ts",
    exposure: "admin",
    methods: ["DELETE", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["credential-check"],
    note: "POST is the login route itself (constant-time username compare + scrypt password verify against ADMIN_PASSWORD_HASH) — cannot require an existing admin-session, since it is what creates one. DELETE clears cookies unconditionally with no prior session check (same no-risk pattern as the dedicated sign-out routes below); documented, not hidden.",
  },
  {
    filePath: "api/admin/sign-out/route.ts",
    exposure: "admin",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: [],
    note: "OPEN FINDING (benign): clears admin session cookies with no session check before doing so. Intentional — logging out an already-unauthenticated caller is a no-op, and clearing cookies carries no confidentiality/integrity risk. Flagged by findUncontrolledMutations as an admin-exposure POST with no session control; documented here rather than silenced.",
  },
  {
    filePath: "api/advisory-applications/route.ts",
    exposure: "public-mutation",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public advisory-board application intake; durable per-IP rate limit (5/30min) + validateAdvisoryApplication() field/length checks. Collects applicant PII.",
  },
  {
    filePath: "api/chat/route.ts",
    exposure: "chat",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public Ask Civica chat proxy to a paid Anthropic model; two-layer (in-memory + durable) per-IP rate limit and hard input-size/shape caps enforced before any model call (2026-06-07 audit remediation).",
  },
  {
    filePath: "api/civica-index/corrections/route.ts",
    exposure: "public-mutation",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public correction-submission intake; per-IP in-memory rate limit (5/10min) + server-side category/dimension/email/length checks. Collects optional submitter PII.",
  },
  {
    filePath: "api/constitution/excerpts/notable/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/constitution/excerpts/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/constitution/passages/[digest]/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/constitution/search/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/contact/route.ts",
    exposure: "public-mutation",
    methods: ["OPTIONS", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["rate-limit", "input-validation"],
    note: "Public contact-form intake; per-IP in-memory rate limit (5/10min) + hand-rolled email/length validation. Collects submitter PII.",
  },
  {
    filePath: "api/countries/[slug]/bills/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/constitution/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/democracy/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/export/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "DAT-027 per-country research export (JSON/CSV); rights-filtered at the resolver layer before rows are emitted. Read-only, no PII.",
  },
  {
    filePath: "api/countries/[slug]/indicator-history/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/international/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/leaders/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/scores/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/countries/[slug]/structure/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/cron/bills/br/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/ca/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/de/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/fr/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/uk/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/bills/us/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/auto-resolve-disputes/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/refresh-cache/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/snapshot-vintage/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-cia-cabinets/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-classifications/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-eurostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-fao-faostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ibge-br/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ilo-ilostat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-imf-weo/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-insee-fr/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-oecd-stat/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-officeholders/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-ons-uk/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-statcan-ca/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-stats-sa/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-un-data/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-undp-hdi/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-unesco-uis/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-us-census/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wdi/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-who-gho/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wikidata/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/sync-wto-stats/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/factbook/verify-reconciliation/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/calculate/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/classify/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/ingest/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/classify/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/cluster/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/ingest/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/review-sla/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/cron/pulse/v2/score/route.ts",
    exposure: "cron",
    methods: ["GET", "POST"],
    mutation: true,
    sensitive: true,
    controls: ["cron-secret"],
    note: "Vercel Cron entrypoint; requireCronAuth() rejects any request without the CRON_SECRET bearer token Vercel sends. GET+POST both wired to the same handler.",
  },
  {
    filePath: "api/governance-evidence/[slug]/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/metrics/[metricId]/strip-data/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/provenance-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/pulse-coding/adjudications/[assignmentId]/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Records a blinded adjudication decision; gated on getPulseCodingSession() with an explicit adjudicator-role check.",
  },
  {
    filePath: "api/pulse-coding/admin/participants/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["admin-session"],
    note: "Issues a pulse-coding participant access code; gated on the OWNER admin session (getAdminSession()), a stronger control than a participant session — this is the coordinator-only provisioning route.",
  },
  {
    filePath: "api/pulse-coding/assignments/[id]/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Saves/locks a blinded coding submission; gated on getPulseCodingSession().",
  },
  {
    filePath: "api/pulse-coding/exports/[studyId]/route.ts",
    exposure: "pulse-coding",
    methods: ["GET"],
    mutation: false,
    sensitive: true,
    controls: ["pulse-coding-session"],
    note: "Exports a coding study artifact; gated on getPulseCodingSession() (any participant), with a further per-study authorization check inside exportPulseCodingStudy() (403 on mismatch).",
  },
  {
    filePath: "api/pulse-coding/session/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: ["credential-check"],
    note: "Pulse-coding sign-in itself (authenticatePulseCodingAccessCode against an issued access code) — cannot require an existing pulse-coding-session, since it is what creates one.",
  },
  {
    filePath: "api/pulse-coding/sign-out/route.ts",
    exposure: "pulse-coding",
    methods: ["POST"],
    mutation: true,
    sensitive: true,
    controls: [],
    note: "OPEN FINDING (benign): clears pulse-coding session cookies with no session check before doing so. Same no-risk logout pattern as /api/admin/sign-out.",
  },
  {
    filePath: "api/reconciliation-audit/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/rights-manifest/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/source-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Public read endpoint backing a country/reader-page data tab; no PII, no auth required by design.",
  },
  {
    filePath: "api/v1/countries/[code]/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/countries/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/elections/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/government-types/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/[country_slug]/history/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/[country_slug]/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/by-government-type/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/compare/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/methodology/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/index/rankings/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/peer-groupings/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/[country_slug]/dimensions/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/[country_slug]/events/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/changelog/v2/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/cluster-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/methodology/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "api/v1/pulse/source-coverage/route.ts",
    exposure: "public-read",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["rate-limit", "public"],
    note: "Public versioned API; CORS-open, per-IP rate limited (RATE_LIMIT_MAX/RATE_LIMIT_WINDOW_MS), no PII.",
  },
  {
    filePath: "downloads/civica-atlas-2026-07-11.json.gz/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Serves the checked, rights-cleared frozen G2 Atlas release archive/manifest from disk. Static, publicly downloadable by design (DAT-017); no auth, no per-request DB access.",
  },
  {
    filePath: "downloads/civica-atlas-2026-07-11.manifest.json/route.ts",
    exposure: "export",
    methods: ["GET"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Serves the checked, rights-cleared frozen G2 Atlas release archive/manifest from disk. Static, publicly downloadable by design (DAT-017); no auth, no per-request DB access.",
  },
  {
    filePath: "embed/[slug]/route.ts",
    exposure: "embed",
    methods: ["GET", "OPTIONS"],
    mutation: false,
    sensitive: false,
    controls: ["public"],
    note: "Legacy iframe embed route; the retired Index composite is no longer served — every request fails closed to a static replacement-link HTML page. No data access.",
  },
];

export function getRouteInventoryEntry(filePath: string): RouteInventoryEntry {
  const entry = ROUTE_INVENTORY.find((r) => r.filePath === filePath);
  if (!entry) throw new Error(`Unknown route inventory entry: ${filePath}`);
  return entry;
}
