import { createHash } from "node:crypto";
import {
  REVIEWER_SELECTION_VERSION,
  type ReviewerLaneId,
} from "./reviewer-selection";

export const REVIEWER_LONGLIST_VERSION = "civica-reviewer-longlist/v1" as const;

type CoreLane = Extract<
  ReviewerLaneId,
  "governance_measurement" | "political_event_data" | "research_data_curation"
>;

export interface ReviewerLonglistCandidate {
  id: string;
  name: string;
  lane: CoreLane;
  currentAffiliation: string;
  institutionalBase: string;
  geographicGroup: "us" | "eu_uk" | "outside_us_eu_uk";
  affiliationSourceUrl: string;
  publicProfessionalContactUrl: string;
  currentActivity: { title: string; year: number; url: string };
  methodContribution: string;
  exactFit: string;
  conflictTier: "manage_and_disclose" | "recuse_overlapping_judgment";
  conflictsAndDependencies: string;
  methodPerspective: string;
  contacted: false;
  verifiedAt: "2026-07-11";
}

export const REVIEWER_LONGLIST = Object.freeze({
  schemaVersion: REVIEWER_LONGLIST_VERSION,
  criteriaVersion: REVIEWER_SELECTION_VERSION,
  status: "verified_public_evidence_no_contact",
  verifiedAt: "2026-07-11",
  contactPolicy:
    "No candidate has been contacted. URLs identify public institutional or professional channels only; they are evidence, not authorization to send a message before GOV-016 and owner approval.",
  limitations: Object.freeze([
    "Public evidence cannot establish availability, willingness, identity beyond the professional record, or a complete conflict disclosure.",
    "Conflict tiers are provisional desk assessments and must be confirmed directly only after the contact gate opens.",
    "The v1 core longlist does not claim comprehensive global coverage. It records qualified perspectives outside the US and EU/UK in every lane and preserves remaining geographic gaps for shortlist decisions.",
  ]),
  candidates: Object.freeze<ReviewerLonglistCandidate[]>([
    {
      id: "gov-a-pemstein",
      name: "Daniel Pemstein",
      lane: "governance_measurement",
      currentAffiliation: "Associate Professor of Political Science and Public Policy, North Dakota State University; V-Dem measurement-methods leadership",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://www.ndsu.edu/research/news/features/dan_pemstein",
      publicProfessionalContactUrl: "https://www.ndsu.edu/research/news/features/dan_pemstein",
      currentActivity: {
        title: "The V-Dem Measurement Model, revised working paper",
        year: 2024,
        url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3595962",
      },
      methodContribution: "Principal designer of V-Dem's Bayesian latent-variable measurement model for expert-coded cross-national data.",
      exactFit: "Can test the Index tournament's treatment of expert disagreement, scale construction, and uncertainty.",
      conflictTier: "recuse_overlapping_judgment",
      conflictsAndDependencies: "Current V-Dem measurement leadership; V-Dem is a Civica input, so pair and recuse on judgments of his own model/source.",
      methodPerspective: "Bayesian latent-variable and expert-coded measurement implementation.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-marquardt",
      name: "Kyle L. Marquardt",
      lane: "governance_measurement",
      currentAffiliation: "Professor of Comparative Politics, University of Bergen; V-Dem Project Manager for Measurement and Methods",
      institutionalBase: "Norway",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.v-dem.net/about/v-dem-project/global-team/kyle-marquardt/",
      publicProfessionalContactUrl: "https://www.v-dem.net/about/v-dem-project/global-team/kyle-marquardt/",
      currentActivity: {
        title: "The V-Dem Measurement Model, revised working paper",
        year: 2024,
        url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3595962",
      },
      methodContribution: "Operational stewardship of expert-coder aggregation, bridge coding, and uncertainty in V-Dem.",
      exactFit: "Can inspect whether Civica propagated measurement uncertainty and coder disagreement faithfully.",
      conflictTier: "recuse_overlapping_judgment",
      conflictsAndDependencies: "Current V-Dem measurement role; disclose, pair, and recuse from deciding whether his own source treatment is adequate.",
      methodPerspective: "Hands-on expert-coding measurement-system implementation.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-claassen",
      name: "Christopher Claassen",
      lane: "governance_measurement",
      currentAffiliation: "Professor of Political Behaviour, University of Glasgow",
      institutionalBase: "United Kingdom",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.gla.ac.uk/schools/socialpolitical/staff/christopherclaassen/",
      publicProfessionalContactUrl: "https://www.gla.ac.uk/schools/socialpolitical/staff/christopherclaassen/",
      currentActivity: {
        title: "Conceptualizing and Measuring Support for Democracy: A New Approach",
        year: 2025,
        url: "https://journals.sagepub.com/doi/10.1177/00104140241259458",
      },
      methodContribution: "Latent measurement of democratic attitudes and downstream analysis with explicit measurement uncertainty.",
      exactFit: "Offers a non-source-lead perspective on construct validity and uncertainty propagation.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Uses major democracy datasets in research; no current Civica-source leadership identified in public evidence.",
      methodPerspective: "Survey/latent-attitude measurement and uncertainty.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-little",
      name: "Andrew T. Little",
      lane: "governance_measurement",
      currentAffiliation: "Associate Professor of Political Science, University of California, Berkeley",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://polisci.berkeley.edu/people/person/andrew-little",
      publicProfessionalContactUrl: "https://polisci.berkeley.edu/people/person/andrew-little",
      currentActivity: {
        title: "Measuring Democratic Backsliding",
        year: 2024,
        url: "https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/measuring-democratic-backsliding/9EE2044CDA598BD815349912E61189D8",
      },
      methodContribution: "Formal critique of expert-coded backsliding measures using observable institutional indicators.",
      exactFit: "Provides an adversarial test of whether composite governance measures add information beyond simpler facts.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica-source leadership identified; a skeptical published position is a perspective, not a disqualifying conflict.",
      methodPerspective: "Formal theory and objective-indicator critique.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-meng",
      name: "Anne Meng",
      lane: "governance_measurement",
      currentAffiliation: "Associate Professor, Department of Politics, University of Virginia",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://www.annemeng.com/",
      publicProfessionalContactUrl: "https://www.annemeng.com/",
      currentActivity: {
        title: "Measuring Democratic Backsliding",
        year: 2024,
        url: "https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/measuring-democratic-backsliding/9EE2044CDA598BD815349912E61189D8",
      },
      methodContribution: "Institutional-indicator measurement of executive constraints, term limits, succession, and backsliding.",
      exactFit: "Can assess Civica's shift from a composite to auditable source-native institutional evidence.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica-source leadership or direct product dependency identified in public evidence.",
      methodPerspective: "Comparative institutions and observable-indicator measurement.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-munck",
      name: "Gerardo L. Munck",
      lane: "governance_measurement",
      currentAffiliation: "Professor, School of International Relations, University of Southern California",
      institutionalBase: "United States; Latin America research perspective",
      geographicGroup: "us",
      affiliationSourceUrl: "https://dornsife.usc.edu/profile/gerardo-munck/",
      publicProfessionalContactUrl: "https://dornsife.usc.edu/profile/gerardo-munck/",
      currentActivity: {
        title: "The State as a Determinant of Democracy",
        year: 2024,
        url: "https://dornsife.usc.edu/profile/gerardo-munck/",
      },
      methodContribution: "Canonical conceptualization-measurement-aggregation framework for evaluating democracy indices.",
      exactFit: "Can judge whether the tournament's construct and aggregation tests support its disposition.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Published critic and former consultant to international organizations including the World Bank; disclose, with no current source leadership identified.",
      methodPerspective: "Conceptual validity, index evaluation, and Latin American comparative politics.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-maerz",
      name: "Seraphine F. Maerz",
      lane: "governance_measurement",
      currentAffiliation: "Senior Lecturer in Political Science (Research Methods), University of Melbourne; V-Dem Research Associate",
      institutionalBase: "Australia",
      geographicGroup: "outside_us_eu_uk",
      affiliationSourceUrl: "https://findanexpert.unimelb.edu.au/profile/1051597-seraphine-maerz",
      publicProfessionalContactUrl: "https://findanexpert.unimelb.edu.au/profile/1051597-seraphine-maerz",
      currentActivity: {
        title: "vdemdata research-software contribution and Decoding Democracy teaching",
        year: 2025,
        url: "https://findanexpert.unimelb.edu.au/profile/1051597-seraphine-maerz",
      },
      methodContribution: "V-Dem data infrastructure, quantitative regime research, computational text analysis, and AI/democracy work.",
      exactFit: "Bridges research-software implementation, democracy measurement, and text-classification concerns.",
      conflictTier: "recuse_overlapping_judgment",
      conflictsAndDependencies: "Current V-Dem Research Associate and former V-Dem faculty; pair and recuse on V-Dem-specific judgments.",
      methodPerspective: "Computational text analysis and research-software implementation from an Australian base.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-a-boese",
      name: "Vanessa A. Boese-Schlosser",
      lane: "governance_measurement",
      currentAffiliation: "Research Fellow, WZB Berlin Social Science Center; V-Dem Research Associate",
      institutionalBase: "Germany",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.wzb.eu/en/press-release/wzb-researcher-vanessa-boese-schlosser-wins-erc-starting-grant-2025",
      publicProfessionalContactUrl: "https://www.wzb.eu/en/persons/vanessa-boese-schlosser",
      currentActivity: {
        title: "ERC Starting Grant: Waves of Regime Transformation",
        year: 2025,
        url: "https://www.wzb.eu/en/press-release/wzb-researcher-vanessa-boese-schlosser-wins-erc-starting-grant-2025",
      },
      methodContribution: "Temporal measurement of regime transformation episodes and democratic decline.",
      exactFit: "Can challenge temporal holdout, regime-transition, and stability claims in the tournament.",
      conflictTier: "recuse_overlapping_judgment",
      conflictsAndDependencies: "V-Dem Research Associate; disclose, pair, and recuse on judgments of her source ecosystem.",
      methodPerspective: "Regime-transformation episodes and early-career political economy.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-brandt",
      name: "Patrick T. Brandt",
      lane: "political_event_data",
      currentAffiliation: "Professor of Political Science, University of Texas at Dallas; Texas AI Research Institute affiliate",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://profiles.utdallas.edu/pbrandt",
      publicProfessionalContactUrl: "https://profiles.utdallas.edu/pbrandt",
      currentActivity: {
        title: "Extractive versus Generative Language Models for Political Conflict Text Classification",
        year: 2025,
        url: "https://www.cambridge.org/core/journals/political-analysis/article/extractive-versus-generative-language-models-for-political-conflict-text-classification/B00077A671DF5656043E4BC45B3864A1",
      },
      methodContribution: "Long-running political event-data and time-series methods plus current domain-adapted LLM classification infrastructure.",
      exactFit: "Can review Pulse's ontology, model architecture, and full extraction/classification pipeline at implementation depth.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Leads adjacent event-data/LLM projects; no Civica source or provider relationship identified.",
      methodPerspective: "Historical event-data infrastructure and modern conflict-language models.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-osorio",
      name: "Javier Osorio",
      lane: "political_event_data",
      currentAffiliation: "Associate Professor, School of Government and Public Policy, University of Arizona",
      institutionalBase: "United States; Latin America research perspective",
      geographicGroup: "us",
      affiliationSourceUrl: "https://sgpp.arizona.edu/person/javier-osorio",
      publicProfessionalContactUrl: "https://sgpp.arizona.edu/person/javier-osorio",
      currentActivity: {
        title: "Machine translation and LLM performance in domain-specific political texts",
        year: 2025,
        url: "https://aclanthology.org/2025.mtsummit-1.24/",
      },
      methodContribution: "Spanish-language supervised event coding, conflict NLP, and cross-lingual model evaluation.",
      exactFit: "Can test Pulse's non-English evidence, translation, and Latin American event-attribution assumptions.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Adjacent ConfliBERT/Eventus work; no Civica source or provider relationship identified.",
      methodPerspective: "Cross-lingual NLP and Latin American violence research.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-dorazio",
      name: "Vito D'Orazio",
      lane: "political_event_data",
      currentAffiliation: "Associate Professor, School of Mathematical and Data Sciences, West Virginia University",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://mathanddata.wvu.edu/directory/faculty/vito-d-orazio",
      publicProfessionalContactUrl: "https://mathanddata.wvu.edu/directory/faculty/vito-d-orazio",
      currentActivity: {
        title: "Multilingual approaches to extractive question answering in political texts",
        year: 2025,
        url: "https://link.springer.com/article/10.1007/s10588-025-09408-2",
      },
      methodContribution: "Production political event coding, ConfliBERT, and Spanish/Arabic political-text extraction.",
      exactFit: "Can inspect multilingual extraction, ontology mapping, and production failure modes.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Co-leads adjacent automated event-data infrastructure; no direct Civica dependency identified.",
      methodPerspective: "Multilingual political NLP from a mathematical/data-science unit.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-weidmann",
      name: "Nils B. Weidmann",
      lane: "political_event_data",
      currentAffiliation: "Professor of Political Science, University of Konstanz",
      institutionalBase: "Germany",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.uni-konstanz.de/centre-for-human-data-society/people/prof-nils-b-weidmann/",
      publicProfessionalContactUrl: "https://www.uni-konstanz.de/centre-for-human-data-society/people/prof-nils-b-weidmann/",
      currentActivity: {
        title: "Ethnic politics via digital means: Introducing the Ethnic Organizations Online dataset",
        year: 2025,
        url: "https://academic.oup.com/jpr/article/62/3/761/8324734",
      },
      methodContribution: "Foundational measurement of media reporting bias and accuracy in conflict event data.",
      exactFit: "Can challenge Pulse's observability, no-event language, and source-coverage assumptions.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or provider relationship identified; adjacent event-data scholarship only.",
      methodPerspective: "Media-selection bias and report-level event analysis.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-pinckney",
      name: "Jonathan Pinckney",
      lane: "political_event_data",
      currentAffiliation: "Assistant Professor of Political Science, University of Texas at Dallas",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://jonathanpinckney.com/",
      publicProfessionalContactUrl: "https://jonathanpinckney.com/#contact",
      currentActivity: {
        title: "Mapping the ROAD to democracy: A global dataset of overturning attempts and organizations in civil resistance transitions",
        year: 2026,
        url: "https://doi.org/10.1093/jopres/xjag002",
      },
      methodContribution: "Supervised NAVCO/SCAD collection and built event datasets for civil resistance and democratic transitions.",
      exactFit: "Can test Pulse's event boundaries, severity/category codebook, and governance-transition coverage.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Own adjacent event datasets; no Civica source or provider relationship identified.",
      methodPerspective: "Civil-resistance event construction and policy-facing applied research.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-radford",
      name: "Benjamin J. Radford",
      lane: "political_event_data",
      currentAffiliation: "Assistant Professor of Political Science, University of Pittsburgh",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://www.polisci.pitt.edu/people/benjamin-radford",
      publicProfessionalContactUrl: "https://www.polisci.pitt.edu/people/benjamin-radford",
      currentActivity: {
        title: "Estimating Conflict Losses and Reporting Biases",
        year: 2023,
        url: "https://www.pnas.org/doi/10.1073/pnas.2307372120",
      },
      methodContribution: "Formal Bayesian measurement of conflict losses, missing reports, and reporting bias.",
      exactFit: "Can test uncertainty and undercount assumptions without conflating reported severity with truth.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or provider relationship identified.",
      methodPerspective: "Bayesian measurement error and conflict forecasting.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-nussio",
      name: "Enzo Nussio",
      lane: "political_event_data",
      currentAffiliation: "Research Professor, Department of Political Science, University of Zurich",
      institutionalBase: "Switzerland; Latin America research perspective",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.ipz.uzh.ch/de/ueber-uns/personen/mitarbeitende/enussi.html",
      publicProfessionalContactUrl: "https://www.ipz.uzh.ch/de/ueber-uns/personen/mitarbeitende/enussi.html",
      currentActivity: {
        title: "Introducing the Lynching in Latin America (LYLA) dataset",
        year: 2025,
        url: "https://journals.sagepub.com/doi/abs/10.1177/00223433231220275",
      },
      methodContribution: "Cross-national event-dataset construction for an underreported violence type with explicit coding and coverage limits.",
      exactFit: "Can evaluate sparse-event ontology design and underreporting in Latin American source environments.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Own adjacent LYLA dataset; no Civica source or provider relationship identified.",
      methodPerspective: "Underreported-event construction and Latin American microdata.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-b-restrepo",
      name: "Jorge A. Restrepo",
      lane: "political_event_data",
      currentAffiliation: "Associate Professor of Economics, Pontificia Universidad Javeriana; Director of CERAC",
      institutionalBase: "Colombia",
      geographicGroup: "outside_us_eu_uk",
      affiliationSourceUrl: "https://perfilesycapacidades.javeriana.edu.co/en/persons/jarestrepo/",
      publicProfessionalContactUrl: "https://perfilesycapacidades.javeriana.edu.co/en/persons/jarestrepo/",
      currentActivity: {
        title: "International verification report on Colombia's peace agreement",
        year: 2025,
        url: "https://www.verificacion.cerac.org.co/wp-content/uploads/2025/04/Decimocuarto-informe-de-verificacion-de-la-implementacion-del-Acuerdo-Final-de-Paz-en-Colombia-v1.pdf",
      },
      methodContribution: "Country-specific conflict monitoring and evidence that global event datasets undercount relative to local microdata.",
      exactFit: "Provides an original-language, non-US/EU audit of source reconciliation, coverage, and local-event loss.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Directs an adjacent independent conflict-data producer; disclose product overlap, with no Civica dependency identified.",
      methodPerspective: "Colombian microdata, local-source reconciliation, and policy verification.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-karcher",
      name: "Sebastian Karcher",
      lane: "research_data_curation",
      currentAffiliation: "Director, Qualitative Data Repository and Center for Qualitative and Multi-Method Inquiry; Research Associate Professor, Syracuse University",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://www.maxwell.syr.edu/directory/sebastian-karcher",
      publicProfessionalContactUrl: "https://www.maxwell.syr.edu/directory/sebastian-karcher",
      currentActivity: {
        title: "Qualitative Data Repository: a national resource for managing qualitative social-science data",
        year: 2025,
        url: "https://news.syr.edu/2025/02/18/qualitative-data-repository-a-national-resource-for-managing-qualitative-data-across-the-social-sciences/",
      },
      methodContribution: "Political-science repository curation, provenance, rights-sensitive access, and open research infrastructure.",
      exactFit: "Can test the Atlas packet against domain-specific repository and sensitive-data practice.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "QDR is a potential repository model, not a Civica source; disclose any future deposit recommendation.",
      methodPerspective: "Qualitative/mixed-method data curation and political-science infrastructure.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-vilhuber",
      name: "Lars Vilhuber",
      lane: "research_data_curation",
      currentAffiliation: "Executive Director, Labor Dynamics Institute, Cornell University; American Economic Association Data Editor",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://economics.cornell.edu/lars-vilhuber",
      publicProfessionalContactUrl: "https://economics.cornell.edu/lars-vilhuber",
      currentActivity: {
        title: "Best Practices for Reproducible Science: Lessons from 2,400 replication packages",
        year: 2025,
        url: "https://cowles.yale.edu/events/2025/best-practices-reproducible-science-lessons-2400-replication-packages-prof-lars-vilhuber",
      },
      methodContribution: "Large-scale replication-package verification, data/code availability policy, and confidentiality-aware reproducibility.",
      exactFit: "Can attempt Civica's clean-room build and distinguish readable documentation from actual reproduction.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "Journal/data-editor role; no Civica source dependency identified.",
      methodPerspective: "Economics journal infrastructure and computational reproduction at scale.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-peer",
      name: "Limor Peer",
      lane: "research_data_curation",
      currentAffiliation: "Associate Director for Research and Strategic Initiatives, Yale Institution for Social and Policy Studies",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://isps.yale.edu/team/limor-peer",
      publicProfessionalContactUrl: "https://isps.yale.edu/team/limor-peer",
      currentActivity: {
        title: "Code Review, Reproducibility, and Improving the Scholarly Record",
        year: 2025,
        url: "https://hdsr.mitpress.mit.edu/pub/suy0nbh5",
      },
      methodContribution: "Data Quality Review workflows combining curation, code review, preservation, and transparency.",
      exactFit: "Can review Civica's evidence, code, and correction chain as one scholarly record.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or repository dependency identified.",
      methodPerspective: "Institutional social-science archive and code-review workflow.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-briney",
      name: "Kristin Briney",
      lane: "research_data_curation",
      currentAffiliation: "Biology and Biological Engineering Librarian, Caltech Library",
      institutionalBase: "United States",
      geographicGroup: "us",
      affiliationSourceUrl: "https://library.caltech.edu/prf.php?account_id=221177",
      publicProfessionalContactUrl: "https://library.caltech.edu/prf.php?account_id=221177",
      currentActivity: {
        title: "The Research Data Management Workbook",
        year: 2025,
        url: "https://caltechlibrary.github.io/RDMworkbook/",
      },
      methodContribution: "Practical data-management planning, documentation, file organization, and data-librarian instruction.",
      exactFit: "Can test whether Civica's codebook and release are usable to a data librarian outside political science.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or repository dependency identified.",
      methodPerspective: "Hands-on research-data library practice across disciplines.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-simons",
      name: "Natasha Simons",
      lane: "research_data_curation",
      currentAffiliation: "Director, National Coordination, Australian Research Data Commons; Research Data Alliance group co-chair",
      institutionalBase: "Australia",
      geographicGroup: "outside_us_eu_uk",
      affiliationSourceUrl: "https://www.rd-alliance.org/members/natasha-simons/",
      publicProfessionalContactUrl: "https://www.rd-alliance.org/members/natasha-simons/",
      currentActivity: {
        title: "ARDC national FAIR-data and persistent-identifier leadership",
        year: 2025,
        url: "https://ardc.edu.au/article/the-ardc-is-helping-lead-the-use-of-data-in-a-fair-way/",
      },
      methodContribution: "National research-data infrastructure, FAIR implementation, policy standardization, and persistent identifiers.",
      exactFit: "Can assess Civica's DOI/versioning, machine-readable manifests, and international data-commons posture.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "National infrastructure and RDA roles; disclose any recommended service relationship.",
      methodPerspective: "National data-commons and international standards governance.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-owango",
      name: "Joy Owango",
      lane: "research_data_curation",
      currentAffiliation: "Founding Director, Training Centre in Communication Africa; Africa PID Alliance co-lead",
      institutionalBase: "Kenya",
      geographicGroup: "outside_us_eu_uk",
      affiliationSourceUrl: "https://www.tcc-africa.org/trustees_board/ms-joy-owango/",
      publicProfessionalContactUrl: "https://www.tcc-africa.org/trustees_board/ms-joy-owango/",
      currentActivity: {
        title: "Global Open Research: Building Equitable and Sustainable Open Science Ecosystems",
        year: 2025,
        url: "https://tccafrica.pubpub.org/pub/z0qgagq9/release/1",
      },
      methodContribution: "African open-science capacity, persistent identifiers, research visibility, and equitable infrastructure adoption.",
      exactFit: "Can test whether Civica's citation and access model works for Global South research users.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "TCC Africa has publisher/open-science partnerships; no Civica source dependency identified.",
      methodPerspective: "African open-science capacity and equitable PID adoption.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-hoces",
      name: "Fernando Hoces de la Guardia",
      lane: "research_data_curation",
      currentAffiliation: "Assistant Project Scientist, Berkeley Initiative for Transparency in the Social Sciences",
      institutionalBase: "United States; Chilean policy-research perspective",
      geographicGroup: "us",
      affiliationSourceUrl: "https://www.bitss.org/people/fernando-hoces-de-la-guardia/",
      publicProfessionalContactUrl: "https://www.bitss.org/people/fernando-hoces-de-la-guardia/",
      currentActivity: {
        title: "Putting Open Science into Practice: 2025 Research Transparency and Reproducibility Training",
        year: 2025,
        url: "https://www.bitss.org/putting-open-science-into-practice-reflections-from-the-2025-rt2-training/",
      },
      methodContribution: "Transparency and reproducibility of policy analysis, meta-research, and reproduction training.",
      exactFit: "Can assess whether the Index preregistration and Atlas reproduction discipline support policy-facing use.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or repository dependency identified.",
      methodPerspective: "Policy-analysis transparency and Latin American research perspective.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
    {
      id: "gov-c-zenk",
      name: "Wolfgang Zenk-Möltgen",
      lane: "research_data_curation",
      currentAffiliation: "Researcher and Deputy Team Lead for Metadata Standards and Interoperability, GESIS",
      institutionalBase: "Germany",
      geographicGroup: "eu_uk",
      affiliationSourceUrl: "https://www.gesis.org/en/institute/about-us/staff/person/wolfgang.zenk-moeltgen",
      publicProfessionalContactUrl: "https://www.gesis.org/en/institute/about-us/staff/person/wolfgang.zenk-moeltgen",
      currentActivity: {
        title: "Metadata for digital behavioral data: the case of Web Tracking and Social Media data",
        year: 2026,
        url: "https://doi.org/10.1515/iwp-2025-2029",
      },
      methodContribution: "Social-science archive metadata standards, interoperability, FAIR assessment, and disclosure-risk management.",
      exactFit: "Can review Civica's codebook, metadata, archive structure, and machine interoperability from a European infrastructure perspective.",
      conflictTier: "manage_and_disclose",
      conflictsAndDependencies: "No Civica source or repository dependency identified.",
      methodPerspective: "European social-science archive metadata and interoperability.",
      contacted: false,
      verifiedAt: "2026-07-11",
    },
  ]),
});

export function reviewerLonglistHash(value: unknown): string {
  return createHash("sha256").update(JSON.stringify(value)).digest("hex");
}

export function reviewerLonglistErrors(
  longlist: typeof REVIEWER_LONGLIST = REVIEWER_LONGLIST,
): string[] {
  const errors: string[] = [];
  if (longlist.schemaVersion !== REVIEWER_LONGLIST_VERSION) errors.push("wrong longlist version");
  if (longlist.criteriaVersion !== REVIEWER_SELECTION_VERSION) errors.push("criteria version drifted");
  const ids = new Set<string>();
  const names = new Set<string>();
  for (const candidate of longlist.candidates) {
    if (ids.has(candidate.id) || names.has(candidate.name)) errors.push(`${candidate.id}: duplicate identity`);
    ids.add(candidate.id);
    names.add(candidate.name);
    if (!candidate.currentAffiliation || !candidate.methodContribution || !candidate.exactFit || !candidate.conflictsAndDependencies || !candidate.methodPerspective)
      errors.push(`${candidate.id}: required evidence field is empty`);
    if (candidate.currentActivity.year < 2023 || candidate.currentActivity.year > 2026)
      errors.push(`${candidate.id}: current activity is outside the verification window`);
    for (const url of [candidate.affiliationSourceUrl, candidate.publicProfessionalContactUrl, candidate.currentActivity.url])
      if (!/^https:\/\//.test(url)) errors.push(`${candidate.id}: non-HTTPS public evidence URL`);
    if (candidate.contacted !== false || candidate.verifiedAt !== "2026-07-11")
      errors.push(`${candidate.id}: contact or verification state drifted`);
  }
  for (const lane of ["governance_measurement", "political_event_data", "research_data_curation"] as const) {
    const candidates = longlist.candidates.filter((candidate) => candidate.lane === lane);
    if (candidates.length < 8) errors.push(`${lane}: fewer than eight candidates`);
    if (!candidates.some(({ geographicGroup }) => geographicGroup === "outside_us_eu_uk"))
      errors.push(`${lane}: no qualified outside-US/EU/UK perspective`);
    if (new Set(candidates.map(({ methodPerspective }) => methodPerspective)).size < 3)
      errors.push(`${lane}: method perspectives are too narrow`);
  }
  const serialized = JSON.stringify(longlist);
  if (/mailto:|@[a-z0-9.-]+\.[a-z]{2,}|\+\d{7,}/i.test(serialized))
    errors.push("private or direct contact data entered the longlist");
  return errors;
}
