import { config } from "dotenv";
import { mkdirSync, writeFileSync } from "node:fs";
import { neon } from "@neondatabase/serverless";
import { researchPanelHash } from "../src/lib/ci/research-panel";
import { K3_LEDGER_AS_OF, K3_LEDGER_CONTRACT, K3_LEDGER_METHOD_VERSION, k3LedgerErrors, runK3LedgerPrototype, type K3TermInput } from "../src/lib/ci/tournament-candidate-k3";
import { INDEX_TOURNAMENT_PROTOCOL_VERSION } from "../src/lib/ci/tournament-preregistration";

config({ path: ".env.local" }); if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
const sql = neon(process.env.DATABASE_URL); const write = process.argv.includes("--write");
export async function buildK3LedgerManifest() {
  const rows = await sql`SELECT j.iso3,j.id::text AS "jurisdictionId",COALESCE(gt.executive_structure,'unknown') AS "executiveStructure",t.id::text AS "termId",o.office_type AS "officeType",o.name AS "officeName",p.id::text AS "personId",p.name AS "personName",t.party_name AS "partyName",to_char(t.start_date,'YYYY-MM-DD') AS "startDate",COALESCE(jsonb_agg(DISTINCT jsonb_build_object('sourceId',st.source_id,'sourceUrl',st.source_url,'sourceHash',st.source_hash,'sourceLicense',st.source_license,'retrievedAt',st.retrieved_at,'predicate',st.predicate)) FILTER (WHERE st.id IS NOT NULL AND st.source_url IS NOT NULL),'[]'::jsonb) AS citations FROM terms t JOIN offices o ON o.id=t.office_id JOIN government_bodies b ON b.id=o.body_id JOIN jurisdictions j ON j.id=b.jurisdiction_id JOIN persons p ON p.id=t.person_id LEFT JOIN LATERAL (SELECT executive_structure FROM government_taxonomies g WHERE g.jurisdiction_id=j.id ORDER BY g.updated_at DESC NULLS LAST,g.created_at DESC NULLS LAST LIMIT 1) gt ON true LEFT JOIN statements st ON st.subject_table='terms' AND st.subject_id=t.id WHERE j.type='sovereign_state' AND j.iso3 IS NOT NULL AND t.is_current=true AND o.office_type IN ('head_of_state','head_of_government') GROUP BY j.iso3,j.id,gt.executive_structure,t.id,o.office_type,o.name,p.id,p.name,t.party_name,t.start_date ORDER BY j.iso3,o.office_type,p.name` as unknown as K3TermInput[];
  const normalized = rows.map((row) => ({ ...row, citations: row.citations.map((citation) => ({ ...citation, retrievedAt: new Date(citation.retrievedAt).toISOString() })) }));
  const outputs = runK3LedgerPrototype(normalized); const errors = k3LedgerErrors(outputs); if (errors.length) throw new Error(errors.join("\n"));
  const represented = new Set(outputs.map((row) => row.iso3));
  return { schemaVersion: "k3-ledger-prototype-manifest/v1", releaseId: "k3-power-transfer-ledger-prototype-v1", candidateId: "K3", methodVersion: K3_LEDGER_METHOD_VERSION, protocolVersion: INDEX_TOURNAMENT_PROTOCOL_VERSION, asOf: K3_LEDGER_AS_OF, contractSha256: researchPanelHash(K3_LEDGER_CONTRACT), inputTerms: rows.length, prototypeRows: outputs.length, observedExecutiveIdentity: outputs.filter((row) => row.executiveIdentityStatus === "observed").length, contestedExecutiveIdentity: outputs.filter((row) => row.executiveIdentityStatus === "contested").length, sovereignJurisdictionsWithoutPrototypeRow: 194 - represented.size, transferStatesComputed: 0, termLimitStatesComputed: 0, everyRowHasStatementCitation: outputs.every((row) => row.citations.length > 0), outputSha256: researchPanelHash(outputs), publicRulebook: "/civica-index/methodology/power-transfer-ledger", publicCountryRows: false, validationStatus: "preregistered_not_executed", valuesLocation: "private_reproducible_from_sourced_terms", publicValuesIncluded: false };
}
async function main() { const manifest = await buildK3LedgerManifest(); if (write) { mkdirSync("data/releases/k3-power-transfer-ledger-prototype-v1", { recursive: true }); writeFileSync("data/releases/k3-power-transfer-ledger-prototype-v1/manifest.v1.json", `${JSON.stringify(manifest, null, 2)}\n`); } console.log(JSON.stringify(manifest, null, 2)); }
if (process.argv[1]?.endsWith("generate-k3-ledger-prototype.ts")) main().catch((error) => { console.error(error); process.exit(1); });
