import { config } from "dotenv";
import { mkdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { neon } from "@neondatabase/serverless";
import { DIMENSION_FEATURES, runDimensionalityAnalysis, type DimensionProfile } from "../src/lib/ci/dimensionality-analysis";
import { CI_TOURNAMENT_PANEL_V3_RELEASE_ID } from "../src/lib/ci/research-panel";

config({ path: ".env.local" }); if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required"); const sql = neon(process.env.DATABASE_URL);
type Input = { iso3: string; year: number; region: string | null; regime: string | null; dimension: string; sourceId: string; indicatorId: string; value: number | null; nativeMin: number; nativeMax: number; isInverted: boolean };

export async function buildIndexDimensionalityAnalysis() {
  const rows = await sql`SELECT j.iso3,p.period_year AS year,j.continent AS region,gt.regime_type_cgv AS regime,p.dimension,p.source_id AS "sourceId",p.indicator_id AS "indicatorId",p.value,p.native_min AS "nativeMin",p.native_max AS "nativeMax",p.is_inverted AS "isInverted" FROM ci_research_panel_rows p JOIN jurisdictions j ON j.id=p.jurisdiction_id LEFT JOIN LATERAL (SELECT regime_type_cgv FROM government_taxonomies g WHERE g.jurisdiction_id=j.id ORDER BY g.regime_year DESC NULLS LAST,g.updated_at DESC NULLS LAST LIMIT 1) gt ON true WHERE p.release_id=${CI_TOURNAMENT_PANEL_V3_RELEASE_ID} ORDER BY j.iso3,p.period_year,p.source_id,p.indicator_id` as unknown as Input[];
  const groups = new Map<string, Input[]>(); for (const row of rows) groups.set(`${row.iso3}:${row.year}`, [...(groups.get(`${row.iso3}:${row.year}`) ?? []), row]);
  const profiles: DimensionProfile[] = [...groups.values()].flatMap((group) => { const byIdentity = new Map(group.map((row) => [`${row.sourceId}:${row.indicatorId}`, row])); const democratic = byIdentity.get("vdem:v2x_libdem")?.value !== null && byIdentity.get("vdem:v2x_libdem")?.value !== undefined ? byIdentity.get("vdem:v2x_libdem") : byIdentity.get("worldbank_wgi:va.est"); const selected = [democratic, byIdentity.get("worldbank_wgi:rl.est"), byIdentity.get("freedom_house:pr_cl_total"), byIdentity.get("transparency_intl:score")]; if (!selected.every((row) => row?.value !== null && row?.value !== undefined)) return []; const first = selected[0]!; return [{ iso3: first.iso3, year: Number(first.year), region: first.region, regime: first.regime, values: selected.map((row) => { const bounded = (Number(row!.value) - Number(row!.nativeMin)) / (Number(row!.nativeMax) - Number(row!.nativeMin)); return (row!.isInverted ? 1 - bounded : bounded) * 100; }) }]; });
  const analysis = runDimensionalityAnalysis(profiles); return { schemaVersion: "civica-index-dimensionality-result/v1", releaseId: "index-dimensionality-analysis-v1", panelReleaseId: CI_TOURNAMENT_PANEL_V3_RELEASE_ID, holdoutOpenedAt: "2026-07-11", holdoutPrerequisite: "K0-K5 implementations and shared interface frozen at commit 4e15744", confirmatoryLabelsUsed: false, ...analysis };
}

export function dimensionalityTable(result: Awaited<ReturnType<typeof buildIndexDimensionalityAnalysis>>) { const rows = [["slice","n","pc1_explained","pc1_democratic_quality","pc1_rule_of_law","pc1_freedom_rights","pc1_corruption_control"], ["pooled",result.pooled.n,result.pooled.explainedVariance[0],...result.pooled.pc1Loadings], ["between_country",result.betweenCountry.n,result.betweenCountry.explainedVariance[0],...result.betweenCountry.pc1Loadings], ["within_country",result.withinCountry.n,result.withinCountry.explainedVariance[0],...result.withinCountry.pc1Loadings], ["first_differences",result.firstDifferences.n,result.firstDifferences.explainedVariance[0],...result.firstDifferences.pc1Loadings], ...result.crossSections.map((row) => [`year_${row.id}`,row.n,row.explainedVariance[0],...row.pc1Loadings]), ...result.timeSlices.map((row) => [`time_${row.id}`,row.n,row.explainedVariance[0],...row.pc1Loadings]), ...result.regions.map((row) => [`region_${row.id}`,row.n,row.explainedVariance[0],...row.pc1Loadings]), ...result.regimes.map((row) => [`regime_${row.id}`,row.n,row.explainedVariance[0],...row.pc1Loadings])]; return `${rows.map((row) => row.map((cell) => typeof cell === "number" ? cell.toFixed(10) : String(cell).replaceAll('"','""')).map((cell) => `"${cell}"`).join(",")).join("\n")}\n`; }
export function dimensionalityFigure(result: Awaited<ReturnType<typeof buildIndexDimensionalityAnalysis>>) { const items = [{ id: "Pooled levels", v: result.pooled.explainedVariance[0] }, { id: "Between countries", v: result.betweenCountry.explainedVariance[0] }, { id: "Within countries", v: result.withinCountry.explainedVariance[0] }, { id: "Annual changes", v: result.firstDifferences.explainedVariance[0] }]; return `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="360" viewBox="0 0 900 360" role="img" aria-labelledby="t d"><title id="t">First component explained variance by analysis level</title><desc id="d">Comparison of pooled, between-country, within-country, and annual-change PCA.</desc><rect width="900" height="360" fill="#fff"/><text x="40" y="42" font-family="sans-serif" font-size="22" fill="#111">PC1 explained variance differs by analysis level</text>${items.map((item,i)=>{const y=85+i*62;const w=item.v*650;return `<text x="40" y="${y+20}" font-family="sans-serif" font-size="15" fill="#222">${item.id}</text><rect x="190" y="${y}" width="650" height="28" fill="#eee"/><rect x="190" y="${y}" width="${w.toFixed(2)}" height="28" fill="#315d73"/><text x="${Math.min(850,200+w).toFixed(2)}" y="${y+20}" font-family="sans-serif" font-size="14" fill="#111">${(item.v*100).toFixed(1)}%</text>`}).join("")}</svg>\n`; }
const sha = (text: string) => createHash("sha256").update(text).digest("hex");
async function main() { const result = await buildIndexDimensionalityAnalysis(); const resultText=`${JSON.stringify(result,null,2)}\n`; const tableText=dimensionalityTable(result); const figureText=dimensionalityFigure(result); const manifest={schemaVersion:"civica-index-dimensionality-artifacts/v1",releaseId:result.releaseId,resultSha256:sha(resultText),tableSha256:sha(tableText),figureSha256:sha(figureText),analysisSha256:result.resultSha256}; const dir = "data/releases/index-dimensionality-analysis-v1"; mkdirSync(dir,{recursive:true}); writeFileSync(`${dir}/result.v1.json`,resultText); writeFileSync(`${dir}/table.v1.csv`,tableText); writeFileSync(`${dir}/pc1-level-comparison.v1.svg`,figureText); writeFileSync(`${dir}/manifest.v1.json`,`${JSON.stringify(manifest,null,2)}\n`); console.log(JSON.stringify({ ...manifest, samples: result.samples, pc1: { pooled: result.pooled.explainedVariance[0], between: result.betweenCountry.explainedVariance[0], within: result.withinCountry.explainedVariance[0], changes: result.firstDifferences.explainedVariance[0] } },null,2)); }
if (process.argv[1]?.endsWith("generate-index-dimensionality-analysis.ts")) main().catch((error)=>{console.error(error);process.exit(1)});
